server:
  port: 9000
  error:
    include-stacktrace: never

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: orders
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show:
        sql: true
  h2:
    console:
      enabled: true
      path: /console/
    datasource:
      url: jdbc:h2:mem:gameshopdb
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#    consumer:
#      properties:
#        spring.json.trusted.packages: "*"
#      bootstrap-servers:
#        - localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.LongSerializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j.circuitbreaker:
  instances:
    orderService:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
    productService:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED