server:
  port: 8888

management:
  health:
    livenessstate.enable: true
    readinessstate.enable: true
  endpoint.health.probes.enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ohanke/game-shop-config
  zipkin:
    base-url: http://zipkin:9411