server:
  port: 8090
  error:
    include-stacktrace: never
  
spring:
  application:
    name: users
    
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show:
        sql: true
  h2:
    console:
      enabled: true
      path: /console/
    datasource:
      url: jdbc:h2:mem:gameshopdb
    
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
#    consumer:
#      properties:
#        spring.json.trusted.packages: "*"
#      bootstrap-servers:
#        - localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.LongSerializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



